- name: "Home"
  link: "/"
- name: "Photos"
  link: "/photos"
- name: "Projects"
  link: "/projects"
- name: "Music"
  link: "/music"
- name: "Instagram"
  link: "/instagram"
- name: "About"
  link: "/about"